version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      YOUTUBE_API_KEY: YOUR_API_KEY
      REDIS_HOST: redis
    depends_on:
      - redis
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
volumes:
  redis_data: