version: '3'
services:
  web:
    build: .
    ports:
      - "7002:8000"
    environment:
      YOUTUBE_API_KEY: YOUR_API_KEY
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./redis_data